### ISSUE TITLE
Aggregate error handling and response checks at one place

### ISSUE THREAD

**Issue by smothiki** [paypal/gorealis#19]
Right now we handle a functions error from the function itself and go to response code check method for handle response validation. These are like two steps and common for every case and should be handled in one aggregate function.

For example 
```
resp,err := somefunc(someargs)
return aggregatefunc(resp,err) should do 
-------
func aggregatefunc(response,error)response,error){
}
```

**Comment by rdelval** [comment]
Finally addressed in PR #51
