### ISSUE TITLE
Specify field names when initializing structs

### ISSUE THREAD

**Issue by pradykaushik** [paypal/gorealis#45]
Currently, struct initialization of structs doesn't specify the field names to which the values are being assigned to. This method of struct initialization strongly depends on one being aware of the order of fields in the struct.

For example, in [job.go](https://github.com/paypal/gorealis/blob/master/job.go#L217), the initialization is done as `aurora.MesosFetcherURI{value, &extract, &cache}`.

Instead, for better readability and to prevent any code breaks, it might be better to initialize structs by also specifying the field names. Like below,

```
aurora.MesosFetcherURI{
    Value: value,
    Extract: &extract,
    Cache: &cache,
}
```

This will also ensure that the addition of new fields in [MesosFetcherURI](https://github.com/paypal/gorealis/blob/master/auroraAPI.thrift#L146) does not break existing code.

**Comment by rdelval** [comment]
Sounds very reasonable. If you can, please send in a patch.
