### ISSUE TITLE
Logging levels

### ISSUE THREAD

**Issue by rdelval** [paypal/gorealis#60]
We need to add a logging library that allows for different levels. 

Following Dave Cheney's blog on logging levels (https://dave.cheney.net/2015/11/05/lets-talk-about-logging), we will be sticking to two levels exclusively: 

INFO and DEBUG

**Comment by at15** [comment]
Are you going to use [logrus](https://github.com/sirupsen/logrus) like dce-go or [uber-go/zap](https://github.com/uber-go/zap) which is faster (claimed to be the fastest but [zerolog](https://github.com/rs/zerolog) disagrees)

**Comment by rdelval** [comment]
Definitely looking at what's currently available. I've looked at [juju/loggo](http://github.com/juju/loggo) and [glog](https://github.com/golang/glog). I hadn't heard of logrus or zerolog and they look very worthy of consideration as well.

**Comment by misho-kr** [comment]
For sanity sake, please don't hardcode any particular logging package. Instead, define a logging interface and provide a way to inject a logger object that implements it.

This should've been done at core package level, but unfortunately it is missing.

**Comment by rdelval** [comment]
As of https://github.com/paypal/gorealis/pull/61 , we have decided to go with a flexible wrapper above a logger interface. This provides a good middle ground and allows the user to use a logging library of the users choice. Thanks to everyone for your inputs, they very much helped paved the way forward on this topic.
